### ISSUE TITLE
Question: does it work with Satel Versa Plus

### ISSUE THREAD

**Issue by fcitc** [druciak/org.openhab.binding.satel#1]
Have anyone tested if it works with Satel Versa Plus internal ETHM module?

**Comment by druciak** [comment]
Hi @fcitc 
I am not aware of any Versa user yet. If it does have integration protocol implemented, it should work. If you have this mainboard, just try it :) Would be nice to know whether it works or not.

**Comment by fcitc** [comment]
Hi @druciak 
thanks for quick response. 
The case is I do not have either too :) but I'm just about to make decision Versa vs Integra.
The ETHM module is the same for both and it should work. 
But I'm eager to choose Integra over Versa due to its flexibility - the price point is almost the same so I think there is no need to investigate it further.
Thanks again - I close this topic.
