### ISSUE TITLE
How to read temperature?

### ISSUE THREAD

**Issue by SchmidtDawid** [druciak/org.openhab.binding.satel#2]
Hi!
I have thermometer module in satel system. How can i read temperature? I configure ETHM-1 and it found my modules. There is my themp module called "Klimatyzator1". But every channels are switches and none looks like temp.

Violation
Tamper
Alarm
Tamper alarm
Alarm memory
Tamper alarm memory
Bypass
No violation trouble
Long violation trouble
Isolate
Masked
Masked memory

Can you help?

**Comment by druciak** [comment]
Hi @SchmidtDawid 
please have a look at this community thread: https://community.openhab.org/t/satel-binding-support-announcements-and-feature-requests
At the top (first post) you have link to the test version of the binding available on Eclipse Marketplace. This version supports ABAX temperature sensors. Follow the documentation to configure it in OH. If you have troubles please post a message in the community thread.

**Comment by SchmidtDawid** [comment]
I have done it. Thank you very much :)
